version: '3'

services:
    mongo:
        container_name: mongo-remap
        image: mongo:4.4.3
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
          - MONGO_INITDB_DATABASE=admin 
        ports:
          - "27017:27017"
        volumes:
          - '/home/ubuntu/mongo/mongo-database:/data/db'
        networks: 
          - mongo-compose-network
 
    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongoex-remap
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongo-remap
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=root
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - ME_CONFIG_MONGODB_AUTH_USERNAME=root
          - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
          - ME_CONFIG_BASICAUTH_USERNAME=root
          - ME_CONFIG_BASICAUTH_PASSWORD=root
        depends_on:
          - "mongo"
        volumes:
          - '/home/ubuntu/mongo/mongo-express:/data/db'
        ports:
          - "8081:8081"
        networks: 
          - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge